---
# - name: Install docker
#   shell: "wget -qO- https://get.docker.com/ | sh"

- name: Install docker requirements
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    state: latest

- name: Add Docker Apt signing key
  apt_key:
    url: https://download.docker.com/linux/{{ansible_distribution|lower}}/gpg
    state: present
    validate_certs: False

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release|lower}} stable"
    

- name: Install docker to use it as runner
  apt:
    name: docker-ce
    state: latest

- name: Start docker
  systemd: 
    state: started 
    name: docker